name: macOS build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Build DaysCountdown
        run: |
          set -eo pipefail
          xcodebuild \
            -project DaysCountdown/DaysCountdown.xcodeproj \
            -scheme DaysCountdown \
            -configuration Release \
            -derivedDataPath build \
            clean build

      - name: Prepare artifact
        run: |
          set -e
          APP_PATH="build/Build/Products/Release/DaysCountdown.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Built app not found at $APP_PATH" >&2
            exit 1
          fi
          mkdir -p artifacts
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" artifacts/DaysCountdown.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DaysCountdown-macOS
          path: artifacts/DaysCountdown.zip
          if-no-files-found: error
